[package]
name = "diesel_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.6", features = ["mysql"] }
dotenvy = "0.15.7"

[[bin]]
name = "show_posts"
doc = false

[[bin]]
name = "write_post"
doc = false

[lib]
doc = false
